language: swift
osx_image: xcode12.5
xcode_workspace: YouMovie/YouMovie.xcworkspace
xcode_sdk: iphonesimulator14.5
env:
 - DESTINATION="platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5" SCHEME="YouMovie"

branches:
  only:
  - master

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/YouMovie-*/
- rvm use $RVM_RUBY_VERSION
- brew update
- brew upgrade swiftlint
- cd YouMovie && pod repo update

script:
- xcodebuild -workspace YouMovie.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" clean test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -t c0d48c88-3d69-4b1d-812a-86305e6087f4
