language: swift
osx_image: xcode11.2
xcode_workspace: YouMovie/YouMovie.xcworkspace
xcode_sdk: iphonesimulator13.2
podfile: YouMovie/Podfile
env:
 - DESTINATION="platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2.2" SCHEME="YouMovie"

branches:
  only:
  - master

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/YouMovie-*/
- rvm use $RVM_RUBY_VERSION
- brew update
- brew upgrade swiftlint
- pod repo update

script:
- xcodebuild -workspace YouMovie/YouMovie.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" clean test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 478b8564-5284-409b-8204-43961fcf963e